In [46]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [1]:
print('Hello World!')

Hello World!


# Function

In [ ]:
# def function_name(parameter_1, parameter_2, ... parameter_n):
#     # your code here to complete the task
#     return result

In [2]:
def power(x, exponent):
    y = x**exponent
    return y
    
z = power(2, 3)
print(z)

8


In [4]:
import numpy as np

# def predict(data):
#     betas = np.array([-26733.12, 87.50, -29192.65, 41420.77, -553.40])
#     return betas[0] + data @ betas[1:]

def predict(data):
    betas = np.array([-26733.12, 87.50, -29192.65, 41420.77, -553.40])
    return np.hstack((np.ones((len(data), 1)), data)) @ betas.T

# Some test code
data = np.array([[4500, 4, 2, 18],
                 [1588, 3, 2, 5],
                 [1714, 2, 1, 4]]) 

print(predict(data))

[323126.62 104713.47 104063.75]


# Class

In [6]:
# class class_name():

#     def instance_method1(self, parameter_1, ..., parameter_n):
#         # do something
#         return # optional

#     def instance_method2(self, parameter_1, ..., parameter_n):
#         # do something
#         return # optional

In [5]:
from sklearn.linear_model import LinearRegression

model_instance = LinearRegression()

In [7]:
# # Constructor Methods

# class class_name():
#     def __init__(self, parameter_1, ..., parameter_n):
#         # Set values here

In [8]:
class Point():
    def __init__(self, x, y):
        self.x = x
        self.y = y

point = Point(10, 20)

print(point.x)

10


In [9]:
class Student():
    """
    A student class that stores/updates info
    """
    # Your code starts here
    def __init__(self, name, sid, email):
        # Initialize the student object by storing the name, sid, email attributes
        self.name = name
        self.sid = sid
        self.email = email
        
    def update_email(self, new):
        # Function to update email of the student
        self.email = new


student1 = Student('Jack', 412345678, 'jack123@gmail.com')
print('Student name: {}, sid: {}, email {}'.format(student1.name, student1.sid, student1.email))

student1.update_email('jack456@gmail.com')
print('Student name: {}, sid: {}, email {}'.format(student1.name, student1.sid, student1.email))

Student name: Jack, sid: 412345678, email jack123@gmail.com
Student name: Jack, sid: 412345678, email jack456@gmail.com


# Linear Algebra

In [10]:
import numpy as np

- ## Transpose
Taking the transpose of a matrix means you switch all the rows and columns - the first row becomes the first column and vice versa for all rows and columns. You can also think of the transpose as flipping all the matrix elements around the diagonal. 

In [11]:
A = np.array([[1, 4, 5],
              [2, 8, 6],
              [3, 1, 4]])

print(A.T)

[[1 2 3]
 [4 8 1]
 [5 6 4]]


- ## Vector Product
The product of vectors is calculated using the inner product which is a way of multiplying them together so that the output is a scalar (not a vector). If you only have two vectors, the inner product becomes the dot product

In [12]:
a = np.array([10, 2, 5])
b = np.array([1, 2, 3])

print(np.dot(a, b))

29


- ## Matrix Product
Note: If matrix A has dimensions (m, n) and matrix B has dimensions (n, p) then A x B will have dimensions (m, p). Note that the number of columns in the first matrix must match the number of rows in the second matrix - if not then the dimensions of the matrix won't agree and multiplying them together won't make sense!

In [13]:
A = np.array([[1, 2],
              [3, 4]])

print('Matmul')
print(np.matmul(A, A))

print('@')
print(A @ A)

Matmul
[[ 7 10]
 [15 22]]
@
[[ 7 10]
 [15 22]]


- ## Matrix Inverse
The inverse of a matrix is denoted using the ^{-1} symbol i.e. the inverse of A is A^{-1}.
</br>Note: some matrices do not have any inverse. If the matrix is not square, or if the determinant of a matrix is 0, then it is not invertible. You can calculate the determinant of your matrix using np.linalg.det

In [14]:
A = np.array([[4, 5, 3],
              [3, 9, 0],
              [2, 7, 9]])

Ainv = np.linalg.inv(A)

print(Ainv)

[[ 0.40909091 -0.12121212 -0.13636364]
 [-0.13636364  0.15151515  0.04545455]
 [ 0.01515152 -0.09090909  0.10606061]]


In [15]:
A = np.array([[3, 6, 12],
              [11, 2, 2],
              [1, 4, 18],
              [2, 8, 10]])

B = np.array([[1, 4, 7],
              [3, 4, 8]])

print(A @ B.T)
# (4, 3) @ (3, 2) = (4, 2)

[[111 129]
 [ 33  57]
 [143 163]
 [104 118]]


In [16]:
a = np.array([2, 4, 6])

b = np.array([1, 2, 3])

print(np.dot(a, b))
# print(a @ b.T)

28


- ## Concatenating arrays

In [18]:
a = np.array([[1, 2],
              [3, 4]])
              
b = np.array([[5, 6],
              [7, 8]])

print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
a = np.array([[1, 2],
              [3, 4]])
              
b = np.array([[5, 6],
              [7, 8]])

print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


- Note: The np.concatenate function as another argument called axis that allows you to specify the joining axis - if axis = 0 the function is equivalent to np.vstack (this is the default) and if axis = 1 the function is equivalent to np.hstack

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))

[1 2 3 4 5 6]


In [25]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.append(a, b))

[1 2 3 4 5 6]


- ## Zeros and Ones

In [30]:
print(np.ones((2, 3)))
print(np.zeros((4, 5)))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


***

In [31]:
# Add Intercept
data = np.array([[5, 7, 10, 4, 1], 
                 [5, 12, 7, 5, 2],
                 [4, 2, 9, 18, 7],
                 [4, 1, 10, 0, 8],
                 [9, 10, 4, 5, 1]])
                 
# Your code here
print(np.hstack((np.ones((data.shape[0], 1)), data)))

[[ 1.  5.  7. 10.  4.  1.]
 [ 1.  5. 12.  7.  5.  2.]
 [ 1.  4.  2.  9. 18.  7.]
 [ 1.  4.  1. 10.  0.  8.]
 [ 1.  9. 10.  4.  5.  1.]]


In [32]:
data = np.array([[5, 7, 10, 4, 1], 
                 [5, 12, 7, 5, 2],
                 [4, 2, 9, 18, 7],
                 [4, 1, 10, 0, 8],
                 [9, 10, 4, 5, 1]])

# Your code here
# print(np.vstack((np.ones((1, data.shape[1])), data)))

ones = np.ones((1, data.shape[1]))
output = np.vstack((ones, data))
print(output)

[[ 1.  1.  1.  1.  1.]
 [ 5.  7. 10.  4.  1.]
 [ 5. 12.  7.  5.  2.]
 [ 4.  2.  9. 18.  7.]
 [ 4.  1. 10.  0.  8.]
 [ 9. 10.  4.  5.  1.]]


In [35]:
A = np.array([[0.625, 0.125],   
              [-0.25, 0.75]])

B = np.array([[1, 4],
              [3, 4]])

C = np.array([[1, 3],
              [2, 2]])

# Your code here
print(A @ B @ np.linalg.inv(C))

print(np.eye(2)) # I

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [36]:
features = np.array([1, 4500, 4, 2, 18])
betas = np.array([-26733.12, 87.50, -29192.65, 41420.77, -553.40])
#                 Beta0      Beta1  Beta2      Beta3     Beta4

# Your code here
print(features @ betas.T)

323126.62


In [37]:
# Your code here
def error_message(username):
    print(f"I'm sorry, {username}. I'm afraid I can't do that.")

In [ ]:
# Your code here
def energy(mass):
    return float(mass * pow(299792458, 2))

# Data Manipulation

In [38]:
import pandas as pd

In [39]:
drinks = pd.read_csv('data/drinks.csv')

In [40]:
drinks.info

<bound method DataFrame.info of          country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol continent  
0                             0.0        AS  
1                             4.9        EU  
2                        

In [41]:
drinks.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [42]:
drinks['beer_servings']

0        0
1       89
2       25
3      245
4      217
      ... 
188    333
189    111
190      6
191     32
192     64
Name: beer_servings, Length: 193, dtype: int64

In [43]:
drinks[drinks['continent']=='EU']

country  beer_servings  spirit_servings  wine_servings  \
1               Albania             89              132             54   
3               Andorra            245              138            312   
7               Armenia             21              179             11   
9               Austria            279               75            191   
10           Azerbaijan             21               46              5   
15              Belarus            142              373             42   
16              Belgium            295               84            212   
21   Bosnia-Herzegovina             76              173              8   
25             Bulgaria            231              252             94   
42              Croatia            230               87            254   
44               Cyprus            192              154            113   
45       Czech Republic            361              170            134   
48              Denmark            224               81            278   
57              Estonia            224              194             59   
60              Finland            263              133             97   
61               France            127              151            370   
64              Georgia             52              100            149   
65              Germany            346              117            175   
67               Greece            133              112            218   
75              Hungary            234              215            185   
76              Iceland            233               61             78   
81              Ireland            313              118            165   
83                Italy             85               42            237   
93               Latvia            281              216             62   
98            Lithuania            343              244             56   
99           Luxembourg            236              133            271   
105               Malta            149              100            120   
111              Monaco              0                0              0   
113          Montenegro             31              114            128   
120         Netherlands            251               88            190   
126              Norway            169               71            129   
135              Poland            343              215             56   
136            Portugal            194               67            339   
139             Moldova            109              226             18   
140             Romania            297              122            167   
147          San Marino              0                0              0   
151              Serbia            283              131            127   
155            Slovakia            196              293            116   
156            Slovenia            270               51            276   
160               Spain            284              157            112   
165              Sweden            152               60            186   
166         Switzerland            185              100            280   
170           Macedonia            106               27             86   
180             Ukraine            206              237             45   
182      United Kingdom            219              126            195   

     total_litres_of_pure_alcohol continent  
1                             4.9        EU  
3                            12.4        EU  
7                             3.8        EU  
9                             9.7        EU  
10                            1.3        EU  
15                           14.4        EU  
16                           10.5        EU  
21                            4.6        EU  
25                           10.3        EU  
42                           10.2        EU  
44                            8.2        EU  
45                           11.8        EU  
48           

In [44]:
drinks[(drinks['continent']=='EU') & (drinks['wine_servings']>300)]

country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312   
61     France            127              151            370   
136  Portugal            194               67            339   

     total_litres_of_pure_alcohol continent  
3                            12.4        EU  
61                           11.8        EU  
136                          11.0        EU

In [45]:
drinks.sort_values('total_litres_of_pure_alcohol')['country'].tail(10)

99             Luxembourg
155              Slovakia
81                Ireland
141    Russian Federation
61                 France
45         Czech Republic
68                Grenada
3                 Andorra
98              Lithuania
15                Belarus
Name: country, dtype: object