# Graph basics and understanding feature aggregation

In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
np.random.seed(0)

N = 4  # set the number of nodes (N) of the graph
A = np.random.randint(2, size=(N, N))  # generate a random matrix with binary elements (unweighted graph)

# to make A symmetric and zero diagonal elements (assumed to have no self-loop in the graph)
A = np.tril(A, -1) # extract all the entries below the main diagonal 
A = A + A.T 
np.fill_diagonal(A,0) # set diagnol to zero

# now A is a valid adjacancy matrix
print(A)

[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]


In [4]:
np.random.seed(0)

# generate the random feature matrix X of the graph
d = 1  # specify the number of features per node
X = np.random.randint(2, size=(N, d))
print(X)

[[0]
 [1]
 [1]
 [0]]


In [5]:
out1 = np.matmul(A, X)  # out1 = AX
out2 = np.matmul(A, out1)  # out2 = A(AX)
print('A:')
print(A)
print('\n')
print('X:')
print(X)
print('\n')
print('AX:')
print(out1)
print('\n')
print('A(AX):')
print(out2)

A:
[[0 1 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 0]]


X:
[[0]
 [1]
 [1]
 [0]]


AX:
[[2]
 [1]
 [1]
 [1]]


A(AX):
[[2]
 [4]
 [3]
 [1]]


In [7]:
# Generate A with self-loop
np.fill_diagonal(A,1)
A

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 1, 0, 1]])

In [8]:
# Examine the result
out1 = np.matmul(A, X)  # out1 = AX
out2 = np.matmul(A, out1)  # out2 = A(AX)
print('A:')
print(A)
print('\n')
print('X:')
print(X)
print('\n')
print('AX:')
print(out1)
print('\n')
print('A(AX):')
print(out2)

A:
[[1 1 1 0]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 0 1]]


X:
[[0]
 [1]
 [1]
 [0]]


AX:
[[2]
 [2]
 [2]
 [1]]


A(AX):
[[6]
 [7]
 [6]
 [3]]


***

# Graph convolutional network from scratch

In [ ]:
class GCN(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        # Add your code here
        self.Linear = nn.Linear(in_features, out_features, bias=False)
        self.bias = nn.Parameter(torch.zeros(out_features))
        # Hints:
        # 1. GCN conduct linear operation over node feature, so a 
        #    standard linear layer will do the job
        # 2. Think about where you add a bias.  You may need organize 
        #    your own bias parameter

    def forward(self, x, A_tilde):
        x = self.Linear(x) # X*W 
        x = torch.matmul(A_tilde, x) # Aggregation  A*x  
        x += self.bias # Add bias

        return x

***

In [ ]:
# Check Core Dataset