# Model with json file

- ## Define the Model

In [64]:
import pandas as pd
import numpy as np
import json

In [65]:
weight_dict = json.load(open('data/parameters_w3.json', 'r'))

In [66]:
def identity(x):
    return x

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class NeuralNetwork():
    
    def __init__(self):
        weight_dict = json.load(open('data/parameters_w3.json', 'r'))
        self.W1 = np.array(weight_dict['0.weight'])
        self.b1 = np.array(weight_dict['0.bias'])
        self.W2 = np.array(weight_dict['1.weight'])
        self.b2 = np.array(weight_dict['1.bias'])

    def predict(self, X):
        y_pred = (self.predict_proba(X) > 0.5).astype(int) # TODO
        return y_pred
    
    def predict_proba(self, X):
        Z2 = X @ self.W1 + self.b1 # TODO
        A2 = identity(Z2) # TODO
        
        Z3 = A2 @ self.W2 + self.b2 # TODO
        a3 = sigmoid(Z3) # TODO

        return a3

- ## Try the Model

In [67]:
model = NeuralNetwork()

df = pd.read_csv('data/test_w3.csv')
df = df.iloc[:, :-1]

cancer_probability = model.predict_proba(df.iloc[0, :])[0] # GENERATE PROBABILITY OF MALIGNANCY 
print(cancer_probability)

cancer_class = model.predict(df.iloc[0, :])[0] # GENERATE CLASS PREDICTION
print(cancer_class)

0.04858943179070452
0


- ## Confusion Matrix

In [68]:
from sklearn.metrics import confusion_matrix

In [69]:
data = pd.read_csv('data/test_w3.csv') 

X = data.iloc[:, :-1] 
y = data.iloc[:, -1]

network = NeuralNetwork() 

test_preds = network.predict(X)

print(confusion_matrix(y, test_preds))

[[76  2]
 [ 2 63]]


- ## Classification Report

In [70]:
from sklearn.metrics import classification_report

In [71]:
print(classification_report(y, test_preds))

              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97        78
         1.0       0.97      0.97      0.97        65

    accuracy                           0.97       143
   macro avg       0.97      0.97      0.97       143
weighted avg       0.97      0.97      0.97       143



# Model in Pytorch

In [72]:
import pandas as pd
import numpy as np
import json
import torch

- ## Linear Layers

In [73]:
import torch
torch.manual_seed(0)

# linear layer from 10 to 5 features with bias (default=True)
mylinear = torch.nn.Linear(10, 5, bias = True)

# applied on some data
N = 3 
d = 10
x = torch.randn(N,d)
print(mylinear(x))
print()

print(mylinear.weight)
print(mylinear.bias)

tensor([[ 0.6288,  1.2646,  0.5846, -0.1577,  0.8414],
        [ 0.9136,  0.8256, -0.0212,  0.1370,  0.6960],
        [ 0.7238,  0.1612, -0.0326,  1.5256, -0.1961]],
       grad_fn=<AddmmBackward0>)

Parameter containing:
tensor([[-0.0024,  0.1696, -0.2603, -0.2327, -0.1218,  0.0848, -0.0063,  0.2507,
         -0.0281,  0.0837],
        [-0.0956, -0.0622, -0.3021, -0.2094, -0.1304,  0.0117,  0.1250,  0.1897,
         -0.2144, -0.1377],
        [ 0.1149,  0.2626, -0.0651,  0.2366, -0.0510,  0.0335,  0.2863, -0.2934,
         -0.1991, -0.0801],
        [-0.1233,  0.2732, -0.2050, -0.1456, -0.2209, -0.2962, -0.1846,  0.2718,
          0.1411,  0.1533],
        [ 0.0166, -0.1621,  0.0535, -0.2953, -0.2285, -0.1630,  0.1995,  0.1854,
         -0.1402, -0.0114]], requires_grad=True)
Parameter containing:
tensor([0.2022, 0.3144, 0.1255, 0.0427, 0.2120], requires_grad=True)


In [74]:
import torch

mylinear = torch.nn.Linear(10, 5, bias = True)

# predefined weight and bias values
weight = torch.zeros(10, 5)
bias = torch.zeros(5)

# set the values!!
mylinear.weight.data = weight
mylinear.bias.data = bias

# check the value of weights and bias now
print(mylinear.weight)
print(mylinear.bias)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)


- ## Activation Functions

In [75]:
import torch
torch.manual_seed(0)

myrelu = torch.nn.ReLU()
mysigmoid = torch.nn.Sigmoid()
mytanh = torch.nn.Tanh()

# try applying activation on the data x below
N = 3
d = 5
x = torch.randn(N,d)
print(x)

# apply relu to x
print(myrelu(x))

# apply sigmoid to x
print(mysigmoid(x))

# apply tanh to x
print(mytanh(x))

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845],
        [-1.3986,  0.4033,  0.8380, -0.7193, -0.4033],
        [-0.5966,  0.1820, -0.8567,  1.1006, -1.0712]])
tensor([[1.5410, 0.0000, 0.0000, 0.5684, 0.0000],
        [0.0000, 0.4033, 0.8380, 0.0000, 0.0000],
        [0.0000, 0.1820, 0.0000, 1.1006, 0.0000]])
tensor([[0.8236, 0.4272, 0.1017, 0.6384, 0.2527],
        [0.1980, 0.5995, 0.6980, 0.3276, 0.4005],
        [0.3551, 0.5454, 0.2980, 0.7504, 0.2552]])
tensor([[ 0.9123, -0.2853, -0.9747,  0.5142, -0.7949],
        [-0.8850,  0.3828,  0.6848, -0.6164, -0.3828],
        [-0.5347,  0.1801, -0.6945,  0.8007, -0.7899]])


- ## Loss Functions

In [76]:
import torch
torch.manual_seed(0)

myMSE = torch.nn.MSELoss()
myBCE = torch.nn.BCELoss() # binary cross entropy for binary classification
myCE = torch.nn.CrossEntropyLoss() # cross entropy for multiclass classification

# calculate BCE for the following prediction
y_true = torch.empty(3).random_(2)
y_pred = torch.sigmoid(torch.randn(3))
print(y_true)
print(y_pred)
print(myBCE(y_pred, y_true))

tensor([0., 1., 1.])
tensor([0.5901, 0.5335, 0.5410])
tensor(0.7115)


- ## Optimizers

In [77]:
import torch

# we need to pass in a list of parameters_w3 to optimizers
W = torch.nn.Parameter(torch.zeros(3,2))
optimizer = torch.optim.SGD([W], lr=1e-5)

- ## Neural Network Model Class

In [78]:
import torch

class myNeuralNetwork(torch.nn.Module):
    def __init__(self, indim):
        super().__init__()
        self.Linear = torch.nn.Linear(indim, 1)
        self.Sigmoid = torch.nn.Sigmoid()

    def forward(self, x):
        x = self.Linear(x)
        x = self.Sigmoid(x)
        return x

***

# Example

In [79]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self):
        super().__init__()   # Previously we dont have this line. Here we are initialising nn.Module
        
        self.Identity = torch.nn.Identity()   # Define activations
        self.Sigmoid = torch.nn.Sigmoid()
        
        self.Linear1 = torch.nn.Linear(30, 10) # Define linear
        self.Linear2 = torch.nn.Linear(10, 1)
        
        # Setting parameter values. In real network training, we dont need this
        weight_dict = json.load(open('data/parameters_w3.json', 'r'))
        W1 = np.array(weight_dict['0.weight'])
        b1 = np.array(weight_dict['0.bias'])
        W2 = np.array(weight_dict['1.weight'])
        b2 = np.array(weight_dict['1.bias'])
        
        self.Linear1.weight.data = torch.from_numpy(W1.T)   
        self.Linear1.bias.data = torch.from_numpy(b1)
        
        self.Linear2.weight.data = torch.from_numpy(W2.T)   
        self.Linear2.bias.data = torch.from_numpy(b2)
        
    def forward(self, X):
        Z2 = self.Linear1(X)      # first layer
        A2 = self.Identity(Z2)     # activation
        
        Z3 = self.Linear2(A2)      # to second layer
        a3 = self.Sigmoid(Z3)      # activation
        return a3

In [80]:
def predict(Y):
    y_pred = (Y > 0.5).astype(int) 
    return y_pred     

In [81]:
import pandas as pd
data = pd.read_csv('data/test_w3.csv') 

person = torch.from_numpy(data.iloc[0,:-1].values)
print(person)

tensor([ 0.2863, -0.8555,  0.2634,  0.1189, -0.8715,  0.1240, -0.2670, -0.2552,
         0.2557, -0.5371, -0.5956, -1.2801, -0.2695, -0.4128, -1.0500,  0.4124,
         0.2242, -0.0035, -0.8483, -0.2156,  0.0657, -1.0292,  0.2400, -0.0980,
        -0.7976,  0.7303,  0.3660,  0.3853,  0.1110,  0.0083],
       dtype=torch.float64)


In [82]:
network = NeuralNetwork() 

cancer_probability = network(person)    
print(cancer_probability[0])

tensor(0.0486, dtype=torch.float64, grad_fn=<SelectBackward0>)


In [83]:
cancer_class = predict(cancer_probability.detach().numpy())[0]
print(cancer_class)

0
